// <auto-generated />
namespace AspNetIdentity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UseraddcolumnProfilePicture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UseraddcolumnProfilePicture));
        
        string IMigrationMetadata.Id
        {
            get { return "202105050608087_User-add-column-ProfilePicture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
